# Generated by Django 3.2.4 on 2021-08-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listing_type',
            field=models.CharField(choices=[('House for Sale', 'House for Sale'), ('Land for Sale', 'Land for Sale'), ('Apartment for rent', 'Apartment for rent')], default='House for Sale', max_length=100),
        ),
    ]
