# Generated by Django 3.2.4 on 2021-08-17 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20210806_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactself9',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactus',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listings',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('Short Term(1-6 months)', 'Short Term(1-6 months)'), ('Long Term(6 months to 1 year)', 'Short Term(6 months to 1 year)')], max_length=200),
        ),
    ]
