# Generated by Django 3.2.4 on 2021-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_auto_20210817_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('Short Term(1-6 months)', 'Short Term(1-6 months)'), ('Long Term(6 months to 1 year)', 'Short Term(6 months to 1 year)')], help_text='Only use this field when listing type is apartment for rent', max_length=200),
        ),
    ]
