# Generated by Django 3.2.4 on 2021-08-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_alter_leaseregistration_location_of_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='listing_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactus',
            name='rent_period',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
