import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import styles from "../styles/About.module.css";
import Footer from '../components/footer/Footer'
import {
  FaPhoneAlt,
  FaEnvelope,
  FaAddressBook,
  FaFacebookF,
  FaInstagram,
  FaTwitter,
} from "react-icons/fa";
import { ToastContainer, toast } from "react-toastify";

const About = () => {
  const router = useRouter();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [message, setMessage] = useState("");

  const handleContactForm = async (e) => {
    e.preventDefault();
    toast.success("Please wait,processing your data");
    const apiUrl = `http://64.227.22.163/api/contact_self9/`;
    const res = await fetch(apiUrl, {
      body: JSON.stringify({
        name: name,
        email: email,
        phone: phone,
        message: message,
      }),
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST",
    });
    const results = await res.json();
    console.log(results);
    setTimeout(() => {
      router.push("/");
    }, 2000);
  };

  return (
      <>
      <Head>
        <title>About Self9City</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/self-9.ico" />
      </Head>
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <div className={styles.videocontainer}>
        <video loop autoPlay muted className={styles.video}>
          <source src="/vids/self9city.mp4" type="video/mp4" />
        </video>
      </div>
      <div className={styles.contactdetails}>
        <div>
          <FaPhoneAlt className={styles.icon} />
          <p>0501095601</p>
        </div>
        <div>
          <FaPhoneAlt className={styles.icon} />
          <p>0552868008</p>
        </div>
        <div>
          <FaAddressBook className={styles.icon} />
          <p>Box GP 3386</p>
        </div>
        <div>
          <FaEnvelope className={styles.icon} />
          <p>info@self9city.com</p>
        </div>
      </div>
      <div className={styles.socialmedia}>
        <a href="https://www.facebook.com" target="_blank" rel="noreferrer">
          <FaFacebookF />
        </a>
        <a href="https://www.instagram.com" target="_blank" rel="noreferrer">
          <FaInstagram />
        </a>
        <a href="https://www.twitter.com" target="_blank" rel="noreferrer">
          <FaTwitter />
        </a>
      </div>
      <hr />
      <div className={styles.aboutmain}>
        <div className={styles.forcontact}>
          <ToastContainer />
          <h3>Contact for more Information</h3>
          <form onSubmit={handleContactForm}>
            <div className={styles.formcontrol}>
              <label htmlFor="name">Name</label>
              <input
                required
                type="text"
                name=""
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </div>
            <div className={styles.formcontrol}>
              <label htmlFor="email">Email</label>
              <input
                required
                type="text"
                name=""
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div className={styles.formcontrol}>
              <label htmlFor="phone">Phone</label>
              <input
                required
                type="text"
                name="phone"
                id=""
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
              />
            </div>
            <div className={styles.formcontrol}>
              <label htmlFor="message">Message</label>
              <input
                required
                type="text"
                name=""
                id="message"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
              />
            </div>
            <br />
            <div className={styles.formcontrol}>
              <button type="submit">Send</button>
            </div>
            <br />
          </form>
        </div>
        <div className={styles.forselfmap}>
          <iframe
            id="gmap_canvas"
            src="https://maps.google.com/maps?q=East%Legon%&t=&z=13&ie=UTF8&iwloc=&output=embed"
          ></iframe>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default About;
