import Head from "next/head";
const Buy = () => {
    return (
        <>
            <Head>
                <title>Buy Your Dream Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/self-9.ico" />
            </Head>
        <div>
            <h2>Buy Page</h2>
        </div>
        </>
    )
}

export default Buy