import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Index.module.css";
import Showcase from '../components/showcase/Showcase'
import Listings from '../components/listings/Listings'

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Listings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/self-9.ico" />
      </Head>
      <div>
        
      <Showcase />
        <h3 className={styles.hometitle}>Homes Just For You</h3>

      <Listings data={data}/>
      </div>
    </div>
  );
}

export async function getServerSideProps(context){

  const res = await fetch("http://64.227.22.163/api/all_listings/");
  const data = await res.json()

  return {
    props:{
      data
    }
  }
}