import Image from "next/image";
import Head from "next/head";
import { FaCalendarAlt, FaShower, AiFillHome } from "react-icons/fa";
import ListingGallery from "../../../components/listinggallery/ListingGallery";
import ContactForm from "../../../components/contactform/Contactform";
import styles from "../../../styles/Index.module.css";

const listingDetail = ({ listingData, galleryListing }) => {
  return (
    <div>
      <Head>
        <title>{listingData.slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/self-9.ico" />
      </Head>
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <div className={styles.mainphotoothers}>
        <div className={styles.mainphoto}>
          <Image
            width={600}
            height={400}
            src={listingData.get_listing_image}
            alt="listing image"
            className={styles.detailimage}
          />
        </div>
        <br />
        <div className={styles.otherimages}>
          <ListingGallery galleryListing={galleryListing} />
        </div>
      </div>
      <hr />
      <div className={styles.details}>
        <div className={styles.price}>
          <h2>{listingData.price}</h2>
          <h3>
            <FaCalendarAlt /> Estimated monthly payment =
            {listingData.can_pay_monthly}
          </h3>
        </div>
        <div className={styles.otherdetails}>
          <div className={styles.detaildetails}>
            <span className={styles.detailroom}>Rooms {listingData.rooms}</span>{" "}
            |
            <span className={styles.detailbath}>baths {listingData.baths}</span>{" "}
            |
            <span className={styles.detailsize}>
              size {listingData.size_of_building}
            </span>
          </div>
          <div className={styles.description}>
            <h3>Full Description</h3>
            <p>{listingData.description}</p>
          </div>
        </div>
      </div>
      <hr />
      <div className={styles.formmap}>
        <ContactForm slug={listingData.slug}/>
        <br />
        <div className={styles.iframe}>
          <br />
          <br />
          <br />
          <iframe
            id="gmap_canvas"
            src={`https://maps.google.com/maps?q=${listingData.full_location}&t=&z=13&ie=UTF8&iwloc=&output=embed`}
          ></iframe>
        </div>
      </div>
      <br />
    </div>
  );
};

export default listingDetail;

export async function getServerSideProps(context) {
  const results = await fetch(
    `http://64.227.22.163/api/listings/${context.params.slug}/`
  );
  const res = await fetch(
    `http://64.227.22.163/api/listing/${context.params.slug}/`
  );
  const listingData = await results.json();
  const galleryListing = await res.json();

  return {
    props: {
      listingData,
      galleryListing,
    },
  };
}

